from materials.prototype.prototype_dark_material import PrototypeDarkMaterial
from materials.prototype.prototype_green_material import PrototypeGreenMaterial
from materials.prototype.prototype_light_material import PrototypeLightMaterial
from materials.prototype.prototype_orange_material import PrototypeOrangeMaterial
from materials.prototype.prototype_purple_material import PrototypePurpleMaterial
from materials.prototype.prototype_red_material import PrototypeRedMaterial
